In [1]:
import pandas as pd


Create Series :

In [2]:
pd.Series(range(10)) #Range means numbers start from 0 till given (no-1)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [3]:
import numpy as np
pd.Series(np.arange(1,11)) #Start from 1 and end point is 11

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [4]:
pd.Series({1:100,2:200,3:300}) #Can create 1D series with dictionary where key act as a index.

1    100
2    200
3    300
dtype: int64

How to create a scalar series, means all values set to constant.
If we have a 10 records and we want to set a constant values to these records rather addding values to every records use scalar option in such a senarios. 

In [5]:
pd.Series('Pune',index=range(10))

0    Pune
1    Pune
2    Pune
3    Pune
4    Pune
5    Pune
6    Pune
7    Pune
8    Pune
9    Pune
dtype: object

Methods related to Series

random.randint(start,stop,frequency) method.

In [6]:
s = pd.Series(np.random.randint(2,12,5)) #means it gives 5 values between 2 and 12 digits
s

0    11
1     5
2     5
3     8
4     8
dtype: int64

drop()
Remove elements from the series based on index.
If we want to remove elements of row then specify index.

In [7]:
s

0    11
1     5
2     5
3     8
4     8
dtype: int64

In [8]:
s.drop(index=4)

0    11
1     5
2     5
3     8
dtype: int64

In [9]:
s


0    11
1     5
2     5
3     8
4     8
dtype: int64

In [10]:
s.drop(index=2, inplace=True)

In [11]:
s

0    11
1     5
3     8
4     8
dtype: int64

In [12]:
#We can also supply multiple indices.
s.drop(index=[0,1])

3    8
4    8
dtype: int64

In [13]:
s

0    11
1     5
3     8
4     8
dtype: int64

The above changes are not permanant because bydefault inplace is false so to make changes permanent we need to mention inplace=True

drop_duplicate()

In [14]:
s.drop_duplicates()

0    11
1     5
3     8
dtype: int64

In [15]:
p = pd.Series(np.random.randint(1,10,10))
p

0    9
1    7
2    2
3    6
4    2
5    5
6    9
7    3
8    8
9    1
dtype: int64

In [16]:
p.drop_duplicates()

0    9
1    7
2    2
3    6
5    5
7    3
8    8
9    1
dtype: int64

In drop_duplicates, it keeps 1st occurence and 2nd occurence will be deleted.\
Also inplace is False bydefault so changes are temporary, keep inplace is True so changes will become permnant.

In [17]:
p

0    9
1    7
2    2
3    6
4    2
5    5
6    9
7    3
8    8
9    1
dtype: int64

In [18]:
p.drop_duplicates(keep='last')

1    7
3    6
4    2
5    5
6    9
7    3
8    8
9    1
dtype: int64

In [19]:
p #bydefault 1st occurace kept but we can change it by keep last, so last element remains and previous will be deleted.

0    9
1    7
2    2
3    6
4    2
5    5
6    9
7    3
8    8
9    1
dtype: int64

In [20]:
#If we want to remove all duplicates.
p


0    9
1    7
2    2
3    6
4    2
5    5
6    9
7    3
8    8
9    1
dtype: int64

In [21]:
p.drop_duplicates(keep=False)  
#All duplicates are removed.

1    7
3    6
5    5
7    3
8    8
9    1
dtype: int64

In [22]:
p

0    9
1    7
2    2
3    6
4    2
5    5
6    9
7    3
8    8
9    1
dtype: int64

In [23]:
import pandas as pd


In [24]:
import numpy as np


In [25]:
s=pd.Series(range(10)) 
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [26]:
dir(s)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__redu

In [27]:
dir(pd.Series)

['T',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '_

In [27]:
# Lets deal with NaN: Not a Number
# when we have missing entries/Empty/Null value 
# then its NaN for pandas

In [29]:
d= pd.Series(range(5))
d

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [31]:
d[1]=np.NaN
d

0    0.0
1    NaN
2    2.0
3    3.0
4    4.0
dtype: float64

In [32]:
# to remove nan
# use dropna
d.dropna()

0    0.0
2    2.0
3    3.0
4    4.0
dtype: float64

#Series : - map()

In [37]:
nm = pd.Series(['Male','Female','Male','Female','Female'])
nm

0      Male
1    Female
2      Male
3    Female
4    Female
dtype: object

In [38]:
nm.map({'Male':0}) #Here, with map we can't replace only one values if we do so other value become Nan 
#to avoid that if we want only one values changed use replace.

0    0.0
1    NaN
2    0.0
3    NaN
4    NaN
dtype: float64

In [34]:
# PS: convert Male to 0 and female 1
# Map values of Series according to input correspondence.
nm.map({'Male':0,'Female':1})

0    0
1    1
2    0
3    1
4    1
dtype: int64

## Series:- replace()

In [35]:
# replace Male as 0 and Female as 1
nm.replace('Male',0)

0         0
1    Female
2         0
3    Female
4    Female
dtype: object

In [36]:
nm.replace({'Male':0,'Female':1})

0    0
1    1
2    0
3    1
4    1
dtype: int64

##nlargest()

In [39]:
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [40]:
# sort  a Series in Descending order
s.nlargest()  #return bydefault 1st 5 largest nos 

9    9
8    8
7    7
6    6
5    5
dtype: int64

In [42]:
s.nlargest(7) #If we want manually set n nos

9    9
8    8
7    7
6    6
5    5
4    4
3    3
dtype: int64

In [43]:
s.nsmallest() #return smallest nos

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [44]:
s.unique() #Find unique records

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
s.value_counts #FInd frequency of unique records.

<bound method IndexOpsMixin.value_counts of 0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64>

In [47]:
x = pd.Series(['A','B','C','A','A','B'])
x

0    A
1    B
2    C
3    A
4    A
5    B
dtype: object

In [48]:
# find out unique records
x.unique()

array(['A', 'B', 'C'], dtype=object)

In [52]:
x.value_counts ## Categorywise count will b given by value_counts

<bound method IndexOpsMixin.value_counts of 0    A
1    B
2    C
3    A
4    A
5    B
dtype: object>

In [53]:
x.nunique() 
# to get a count of unique reocrds use nunique()
# returns a count of unique records

3

## Convert a Series into....

In [54]:
s.to_numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
s.to_csv('number.csv',index=False)

In [56]:
s.to_dict()

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9}

In [57]:
dict(s)

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9}

In [58]:
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [59]:
#convert a Series to list
list(s)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [60]:
s.to_list()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [61]:
a = pd.DataFrame({1:[100,200],2:[300,400]})
a

1    2
0  100  300
1  200  400

In [64]:
# convert a DataFrame to list
a.values

array([[100, 300],
       [200, 400]])

In [67]:
a.values.tolist()

[[100, 300], [200, 400]]

In [68]:
a

1    2
0  100  300
1  200  400

In [69]:
a.to_dict()
 #returns dict of dictionary

{1: {0: 100, 1: 200}, 2: {0: 300, 1: 400}}

In [70]:
dict(a)
# returns Series if dictionary

{1: 0    100
 1    200
 Name: 1, dtype: int64,
 2: 0    300
 1    400
 Name: 2, dtype: int64}